---
- name: Install required s/w's for ci-cd
  hosts: all
  tasks:
   - name: Install s/w's
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
      - {a: tomcat9,b: no}
      - {a: tomcat9-admin,b: no}
- name: Continuous Download and Continuous Build
  hosts: devserver
  tasks:
   - name: Downlaod the devlopment code
     git:
      repo: https://github.com/intelliqittrainings/maven.git
      dest: mygit
   - name: Create an artifact
     shell: cd mygit;mvn package
   - name: Fetch the artifact from devserver to contoller
     fetch:
      src: mygit/webapp/target/webapp.war
      dest: /tmp
- name: Continuous Deployment and Continuous Testing
  hosts: qaserver
  tasks:
   - name: Copy the artifact into the tomcat on qaserver
     copy:
      src: /tmp/172.31.6.85/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat9/webapps/testapp.war
   - name: Download the selenium scripts
     git:
      repo: https://github.com/intelliqittrainings/FunctionalTesting.git
      dest: test-git
   - name: Run the selenium scripts
     shell: java -jar test-git/testing.jar
- name: Continuous Delivery
  hosts: prodserver
  tasks:
   - name: Copy the artifact into the tomcat on prodserver
     copy:
      src: /tmp/172.31.6.85/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat9/webapps/prodapp.war
...







